import { LayoutData } from "./store";

export const MOCK_ANALYSIS = {
  rooms: [
    {
      type: "kitchen",
      confidence: 0.97,
      approximate_size: "medium",
      features: ["window", "door", "corner"],
    },
    {
      type: "living_room",
      confidence: 0.95,
      approximate_size: "large",
      features: ["window", "door", "corner"],
    },
    {
      type: "bedroom",
      confidence: 0.91,
      approximate_size: "medium",
      features: ["window", "door"],
    },
  ],
  overall_layout: "open_plan",
  image_quality: "floor_plan",
};

export const MOCK_LAYOUT: LayoutData = {
  layout_id: "demo-sukimeh-2026",
  score: 98,
  rooms: MOCK_ANALYSIS.rooms as any,
  furniture_placements: [
    {
      product_id: "ELB-HOOD-X5",
      name: "Elba Smart Hood X5",
      room: "kitchen",
      x_percent: 65,
      y_percent: 15,
      rotation: 0,
      annotation: "Airflow Optimized",
      icon: "🔥",
    },
    {
      product_id: "ELB-HOB-G4",
      name: "Elba Gas Hob G4 Pro",
      room: "kitchen",
      x_percent: 55,
      y_percent: 22,
      rotation: 0,
      annotation: "Work Triangle Aligned",
      icon: "🍳",
    },
    {
      product_id: "ELB-FRIDGE-S2",
      name: "Elba Side-by-Side Fridge S2",
      room: "kitchen",
      x_percent: 25,
      y_percent: 14,
      rotation: 0,
      annotation: "Entry Accessible",
      icon: "🧊",
    },
    {
      product_id: "ELB-DW-A3",
      name: "Elba Dishwasher A3",
      room: "kitchen",
      x_percent: 40,
      y_percent: 20,
      rotation: 0,
      annotation: "Plumbing Adjacent",
      icon: "🫧",
    },
    {
      product_id: "CH-WIFI-R1",
      name: "Chin Hin Smart WiFi Router R1",
      room: "living_room",
      x_percent: 50,
      y_percent: 50,
      rotation: 0,
      annotation: "WiFi Optimal — Central Position",
      icon: "📡",
    },
    {
      product_id: "CH-SOFA-L2",
      name: "Chin Hin L-Shape Sofa L2",
      room: "living_room",
      x_percent: 50,
      y_percent: 68,
      rotation: 0,
      annotation: "Optimal Viewing Distance",
      icon: "🛋️",
    },
    {
      product_id: "CH-TV-65X",
      name: 'Chin Hin 65" Smart TV X-Series',
      room: "living_room",
      x_percent: 50,
      y_percent: 22,
      rotation: 0,
      annotation: "Glare-Free Position",
      icon: "📺",
    },
    {
      product_id: "CH-CT-W1",
      name: "Chin Hin Walnut Coffee Table",
      room: "living_room",
      x_percent: 50,
      y_percent: 50,
      rotation: 0,
      annotation: "Traffic Flow Clear",
      icon: "☕",
    },
    {
      product_id: "CH-BED-K1",
      name: "Chin Hin King Bed Frame K1",
      room: "bedroom",
      x_percent: 50,
      y_percent: 58,
      rotation: 0,
      annotation: "Headboard Against Wall",
      icon: "🛏️",
    },
    {
      product_id: "CH-WD-S3",
      name: "Chin Hin Sliding Wardrobe S3",
      room: "bedroom",
      x_percent: 15,
      y_percent: 30,
      rotation: 0,
      annotation: "60cm Clearance Maintained",
      icon: "🚪",
    },
    {
      product_id: "CH-SENS-C1",
      name: "Chin Hin Smart Sensor C1",
      room: "bedroom",
      x_percent: 50,
      y_percent: 10,
      rotation: 0,
      annotation: "Full Room Coverage",
      icon: "📡",
    },
    {
      product_id: "CH-FAN-D5",
      name: "Chin Hin Smart Ceiling Fan D5",
      room: "living_room",
      x_percent: 72,
      y_percent: 42,
      rotation: 0,
      annotation: "Central Airflow",
      icon: "🌀",
    },
  ],
  smart_optimizations: [
    {
      type: "airflow",
      title: "Optimized Airflow",
      desc: "Hood diletak berhampiran tingkap untuk ventilasi 30% lebih baik. Work triangle (hood-hob-fridge) dijaga di bawah 6m.",
    },
    {
      type: "wifi",
      title: "Dead Zone Elimination",
      desc: "Router dipusatkan di kedudukan geometri rumah — liputan WiFi 6E penuh merentasi semua bilik.",
    },
    {
      type: "traffic",
      title: "Traffic Flow Clear",
      desc: "Laluan 90cm tanpa halangan dari pintu masuk ke semua zon. Tiada perabot menghalang pintu.",
    },
  ],
  bundle: {
    products: [
      {
        id: "ELB-HOOD-X5",
        name: "Elba Smart Hood X5",
        price: 1299,
        original_price: 1599,
        thumbnail: "/products/elba-hood-x5.jpg",
        sku: "ELB-HOOD-X5",
      },
      {
        id: "ELB-HOB-G4",
        name: "Elba Gas Hob G4 Pro",
        price: 899,
        original_price: 1099,
        thumbnail: "/products/elba-hob-g4.jpg",
        sku: "ELB-HOB-G4",
      },
      {
        id: "ELB-FRIDGE-S2",
        name: "Elba Side-by-Side Fridge S2",
        price: 2499,
        original_price: 2999,
        thumbnail: "/products/elba-fridge-s2.jpg",
        sku: "ELB-FRIDGE-S2",
      },
      {
        id: "ELB-DW-A3",
        name: "Elba Dishwasher A3",
        price: 1599,
        original_price: 1899,
        thumbnail: "/products/elba-dw-a3.jpg",
        sku: "ELB-DW-A3",
      },
      {
        id: "CH-WIFI-R1",
        name: "Chin Hin Smart WiFi Router R1",
        price: 349,
        original_price: 449,
        thumbnail: "/products/ch-wifi-r1.jpg",
        sku: "CH-WIFI-R1",
      },
      {
        id: "CH-SOFA-L2",
        name: "Chin Hin L-Shape Sofa L2",
        price: 1899,
        original_price: 2399,
        thumbnail: "/products/ch-sofa-l2.jpg",
        sku: "CH-SOFA-L2",
      },
      {
        id: "CH-TV-65X",
        name: 'Chin Hin 65" Smart TV X-Series',
        price: 2199,
        original_price: 2699,
        thumbnail: "/products/ch-tv-65x.jpg",
        sku: "CH-TV-65X",
      },
      {
        id: "CH-BED-K1",
        name: "Chin Hin King Bed Frame K1",
        price: 1499,
        original_price: 1899,
        thumbnail: "/products/ch-bed-k1.jpg",
        sku: "CH-BED-K1",
      },
      {
        id: "CH-WD-S3",
        name: "Chin Hin Sliding Wardrobe S3",
        price: 1799,
        original_price: 2199,
        thumbnail: "/products/ch-wd-s3.jpg",
        sku: "CH-WD-S3",
      },
      {
        id: "CH-FAN-D5",
        name: "Chin Hin Smart Ceiling Fan D5",
        price: 449,
        original_price: 549,
        thumbnail: "/products/ch-fan-d5.jpg",
        sku: "CH-FAN-D5",
      },
    ],
    total_original: 17790,
    total_discounted: 14490,
  },
};
